export const ADD_USER_CHOICE = "ADD_USER_CHOICE";
export const FETCH_TRIVIA_QUESTIONS_SUCCESS = "FETCH_TRIVIA_QUESTIONS_SUCCESS";
export const FETCH_TRIVIA_QUESTIONS_FAILURE = "FETCH_TRIVIA_QUESTIONS_FAILURE";
export const RESET_USER_CHOICES = "RESET_USER_CHOICES";
export const RESET_TRIVIA_QUESTIONS = "RESET_TRIVIA_QUESTIONS";
